### ISSUE TITLE
to do in the code

### ISSUE THREAD

**Issue by marcellabonazzoli** [xclaeys/ElastoPhi#1]
- controller si export (avec les modifs de vendredi) marche (pour le moment pour moi le fichier visu créé ne s'ouvre pas)    
- ajouter le cpp de testcluster ou l'enlever de Cmakelist

**Comment by PierreMarchand20** [comment]
Pas de problème concernant l'export apparemment.
test_cluster ajouté

**Comment by PierreMarchand20** [comment]
bug trouvé dans la fonction exportgmsh, ne marche pas pour certains meshes

**Comment by marcellabonazzoli** [comment]
bug corrigé
